services:
  - type: web
    name: stream-app
    env: node
    rootDir: .
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://ott-u3vw.onrender.com
      - key: VITE_API_URL
        value: https://ott-u3vw.onrender.com
