const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const playlistSchema = new Schema({
  channel: {
    type: Schema.Types.ObjectId,
    ref: "Channel",
    required: true,
    index: 1
  },
  name: {
    type: String,
    required: true,
    trim: true
  },
  description: {
    type: String,
    default: ""
  },
  isPrivate: {
    type: Boolean,
    default: false
  },
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  autoCriteria: {
    genre: { type: Schema.Types.ObjectId, ref: "Genre" },
    minRating: Number
  },
  items: [{
    itemId: { type: Schema.Types.ObjectId, required: true },
    itemType: { type: String, enum: ["Movie", "TvShow", "WebSeries"], required: true },
    addedAt: { type: Date, default: Date.now }
  }],
  isDeleted: {
    type: Boolean,
    default: false,
    index: 1
  }
}, {
  timestamps: true
});

module.exports = mongoose.model("Playlist", playlistSchema);
